import assert from 'node:assert/strict'; import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path';
import {compileWeeklyReport} from '../reporting/weekly_owner/lib/compile.mjs'; import {renderText} from '../reporting/weekly_owner/lib/render.mjs'; import {sendWeeklyEmail} from '../reporting/weekly_owner/providers/http-email.mjs';
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'cn8-')); const put=(p,o)=>{const f=path.join(tmp,p);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,JSON.stringify(o))};
put('state/health/network.json',{overall:'UNVERIFIED',employees:{marcus_vale:'UNVERIFIED',nia_brooks:'UNVERIFIED',camille_rose:'UNVERIFIED',maya_reyes:'UNVERIFIED'}}); put('state/distribution.json',{jobs:[{employee:'marcus_vale',state:'SCHEDULED',publish_at:'2026-09-19T12:00:00Z'},{employee:'nia_brooks',state:'SENT',confirmed_at:'2026-09-18T12:00:00Z'},{employee:'camille_rose',state:'FAILED',updated_at:'2026-09-17T12:00:00Z'}]}); put('state/pipeline.json',{minimum_coverage_days:null}); put('health/incidents/ledger.json',{incidents:[{id:'x',status:'RECOVERED',recovery:'retry'}]}); put('state/budget.json',{}); for(const id of ['marcus_vale','nia_brooks','camille_rose','maya_reyes']) put(`employees/${id}/health.json`,{overall:'UNVERIFIED',checks:{}});
const r=compileWeeklyReport({root:tmp,start:'2026-09-14',end:'2026-09-20',now:'2026-09-20T12:00:00Z'}); assert.equal(r.network_health,'UNVERIFIED'); assert.equal(r.summary.released,1); assert.equal(r.summary.failed_or_missed,1); assert.equal(r.summary.automatically_recovered,1); assert.equal(r.owner_action_required,'NONE'); assert.equal(r.employees.length,4); assert.match(renderText(r),/OWNER ACTION REQUIRED: NONE/); assert.notEqual(r.health.certification,'VERIFIED');
const disabled=await sendWeeklyEmail({subject:'x',text:'x',env:{}}); assert.equal(disabled.status,'SKIPPED_DISABLED');
const missing=await sendWeeklyEmail({subject:'x',text:'x',env:{WEEKLY_REPORT_DELIVERY_ENABLED:'true'}}); assert.equal(missing.status,'BLOCKED_MISSING_CONFIG');
let body; const sent=await sendWeeklyEmail({subject:'s',text:'t',env:{WEEKLY_REPORT_DELIVERY_ENABLED:'true',WEEKLY_EMAIL_ENDPOINT:'https://example.test',WEEKLY_EMAIL_TOKEN:'k',WEEKLY_OWNER_EMAIL:'o@example.test',WEEKLY_REPORT_FROM:'r@example.test'},fetchImpl:async(u,o)=>{body=JSON.parse(o.body);return {ok:true,status:200}}}); assert.equal(sent.status,'SENT'); assert.equal(body.to[0],'o@example.test');
console.log('Phase 8 behavioral tests: 11/11 PASS');
