const EVENTS = new Set(['creator_landing','content_click','lead_started','lead_completed','email_captured','tool_started','checkout_started','purchase_completed','qualified_lead']);
const KEYS = ['src_creator','src_platform','src_experiment','src_icp','src_franchise','src_cta'];
const enc = new TextEncoder();
function json(data,status=200,extra={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...extra}})}
function safeString(v,max=160){return typeof v==='string' ? v.trim().slice(0,max) : ''}
function validAttribution(a){return a && KEYS.every(k=>safeString(a[k]).length>0)}
function sanitizeProperties(p){if(!p||typeof p!=='object'||Array.isArray(p))return {}; const out={}; const allowed=['destination','session_id','value','currency','product','vertical','path','referrer_host']; for(const k of allowed){if(!(k in p))continue; const v=p[k]; if(k==='value'){if(typeof v==='number'&&Number.isFinite(v)&&v>=0)out[k]=v;} else out[k]=safeString(v,300);} return out;}
async function digest(text){const b=await crypto.subtle.digest('SHA-256',enc.encode(text));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function handleEvent(req,env){let body;try{body=await req.json()}catch{return json({ok:false,error:'invalid_json'},400)} const event=safeString(body.event,64); if(!EVENTS.has(event))return json({ok:false,error:'invalid_event'},400); const eventId=safeString(body.event_id,128); if(!eventId)return json({ok:false,error:'event_id_required'},400); const attr=body.attribution; if(!validAttribution(attr))return json({ok:false,error:'complete_attribution_required'},400); const occurred=safeString(body.occurred_at,64); if(!occurred||Number.isNaN(Date.parse(occurred)))return json({ok:false,error:'valid_occurred_at_required'},400); const normalized={event,event_id:eventId,occurred_at:new Date(occurred).toISOString(),received_at:new Date().toISOString(),attribution:Object.fromEntries(KEYS.map(k=>[k,safeString(attr[k])])),properties:sanitizeProperties(body.properties)}; normalized.dedupe_key=await digest(`${event}:${eventId}`);
 if(env.ATTRIBUTION_DB){try{await env.ATTRIBUTION_DB.prepare(`INSERT OR IGNORE INTO creator_events (dedupe_key,event_id,event,occurred_at,received_at,src_creator,src_platform,src_experiment,src_icp,src_franchise,src_cta,properties_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)`).bind(normalized.dedupe_key,eventId,event,normalized.occurred_at,normalized.received_at,...KEYS.map(k=>normalized.attribution[k]),JSON.stringify(normalized.properties)).run();}catch(e){return json({ok:false,error:'persistence_failed'},503)}} else if(env.ATTRIBUTION_SINK){await env.ATTRIBUTION_SINK.put(normalized.dedupe_key,JSON.stringify(normalized));} else {return json({ok:false,error:'persistence_unconfigured'},503)}
 return json({ok:true,event_id:eventId,dedupe_key:normalized.dedupe_key},202);
}
export default {async fetch(req,env){const u=new URL(req.url); if(req.method==='GET'&&u.pathname==='/health')return json({ok:true,service:'creator-network-attribution',persistence:Boolean(env.ATTRIBUTION_DB||env.ATTRIBUTION_SINK)}); if(req.method==='POST'&&u.pathname==='/v1/events')return handleEvent(req,env); if(req.method==='OPTIONS')return new Response(null,{status:204,headers:{'access-control-allow-origin':env.CORS_ORIGIN||'https://invalid.local','access-control-allow-methods':'POST,OPTIONS','access-control-allow-headers':'content-type','access-control-max-age':'86400'}}); return json({ok:false,error:'not_found'},404)}};
