// Renders the owner's signup kit from distribution/config/signup-kit.json: docs/SIGNUP_KIT.md + a 400x400 avatar per
// creator (derived from the approved face_front). No credentials involved; nothing here is secret. Re-run after editing
// the JSON:   npm run signup:kit
import fs from 'node:fs';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
const kit=JSON.parse(fs.readFileSync('distribution/config/signup-kit.json'));
const disc=JSON.parse(fs.readFileSync('distribution/config/buffer-discovery.json'));
const ids=Object.keys(kit.creators);const lines=[];const p=(s='')=>lines.push(s);
p('# Signup kit — the four creators\' social accounts (owner-only)');p();
p(`Generated by \`scripts/signup-kit.mjs\` from \`distribution/config/signup-kit.json\` — edit the JSON, not this file.`);
p(`Why owner-only: signup needs SMS + CAPTCHA on real hardware; automating it flags the accounts at birth (ledger named stop).`);p();
p('## Order');p(kit.platform_order.map((x,i)=>`${i+1}. **${x}**`).join(' → '));p();p(kit.platform_order_why);p();
p('## Rules that apply to every account');
p('- **Use the creator\'s own email** (inbound routes to your inbox via Cloudflare Email Routing — verification codes arrive there). One phone number can verify several Instagram/Threads accounts; TikTok and X may ask for a distinct number per account — use your second line if prompted.');
p('- **Bio ends with the disclosure line** `'+kit.disclosure_line+'` on every platform (FTC 2026 AI-likeness disclosure; also required for Meta/TikTok AI-content labels).');
p('- **Avatar** = `avatar_400.png` in the creator\'s references folder (the approved `face_front`, 400×400). Same image on every platform — identity lock.');
p('- **Display name** exactly as given; **handle** first choice, fall back to the second, otherwise append `.official`. Record the handle you got in the table at the bottom.');
p('- **Birthday**: the year given, any day — it must be consistent across platforms for the same creator.');
p('- Skip "find contacts", skip "suggested follows", do not link to your personal accounts.');p();
for(const id of ids){const c=kit.creators[id];const d=disc.creators.find(x=>x.creator_id===id);const ref=`media/identities/${id}/references/face_front.png`;const out=`media/identities/${id}/references/avatar_400.png`;
 execFileSync('sips',['-z','400','400',ref,'--out',out],{stdio:'ignore'});const sha=crypto.createHash('sha256').update(fs.readFileSync(out)).digest('hex').slice(0,12);
 p(`## ${c.display_name} — \`${id}\``);p();
 p('| Field | Value |');p('|---|---|');
 p(`| Email | \`${c.email}\` (Buffer account: \`${d.account_email}\`) |`);
 p(`| Handle | \`@${c.handles[0]}\` — fallback \`@${c.handles[1]}\` |`);
 p(`| Display name | ${c.display_name} |`);
 p(`| Link | ${c.link} |`);
 p(`| Birth year | ${c.birth_year} |`);
 p(`| Avatar | \`${out}\` (sha256 ${sha}…) |`);
 p(`| Bio — TikTok (${c.bio.short.length}/${kit.bio_limits.tiktok}) | ${c.bio.short} |`);
 p(`| Bio — Instagram / Threads (${c.bio.long.length}/${kit.bio_limits.instagram}) | ${c.bio.long} |`);
 p(`| Bio — X (${c.bio.long.length}/${kit.bio_limits.x}) | ${c.bio.long} |`);
 p(`| Buffer org | \`${d.organizations[0].id}\` (already exists — connect channels there) |`);p();}
p('## After each creator: connect to Buffer');
p('1. Log in to Buffer **as that creator** (their email — four separate Buffer accounts, never consolidated).');
p('2. Channels → Connect → choose the platform → authorise with the account you just created.');
p('3. Repeat for Threads, Instagram, TikTok, X, YouTube as available.');
p('4. Tell me "channels connected for <name>" — I re-run `python3 scripts/vault-exec.py -- node scripts/buffer-discovery.mjs`, which records the channel ids and lifts the named stop for that creator.');p();
p('## Record what you got');p('| Creator | Threads | Instagram | TikTok | X | YouTube |');p('|---|---|---|---|---|---|');
for(const id of ids)p(`| ${kit.creators[id].display_name} | | | | | |`);
fs.writeFileSync('docs/SIGNUP_KIT.md',lines.join('\n')+'\n');console.log('docs/SIGNUP_KIT.md +',ids.length,'avatars');
